version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"

  backend:
    build:
      context: ./backend
    ports:
      - "4001:4001"
    depends_on:
      - database

  database:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: example_db
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
