const cards = [
    { id: 1, image: 'Deals-card-1.png', title: 'Madrid', rate: '4.8', country: 'Spain', oldprice: '950', price: '850'},
    { id: 2, image: 'Deals-card-2.png', title: 'Firenze', rate: '4.5', country: 'Italy', oldprice: '850', price: '750'},
    { id: 3, image: 'Deals-card-3.png', title: 'Paris', rate: '4.4', country: 'France', oldprice: '699', price: '599'},
    { id: 4, image: 'Deals-card-4.png', title: 'London', rate: '4.8', country: 'UK', oldprice: '950', price: '850'},
    { id: 5, image: 'Deals-card-4.png', title: 'London', rate: '4.8', country: 'UK', oldprice: '950', price: '850'},
    { id: 6, image: 'Deals-card-4.png', title: 'London', rate: '4.8', country: 'UK', oldprice: '950', price: '850'},
    { id: 7, image: 'Deals-card-4.png', title: 'London', rate: '4.8', country: 'UK', oldprice: '950', price: '850'},
    { id: 8, image: 'Deals-card-4.png', title: 'London', rate: '4.8', country: 'UK', oldprice: '950', price: '850'},
    { id: 9, image: 'Deals-card-3.png', title: 'Paris', rate: '4.4', country: 'France', oldprice: '699', price: '599'},
    { id: 10, image: 'Deals-card-3.png', title: 'Paris', rate: '4.4', country: 'France', oldprice: '699', price: '599'},
    { id: 11, image: 'Deals-card-3.png', title: 'Paris', rate: '4.4', country: 'France', oldprice: '699', price: '599'},
    { id: 12, image: 'Deals-card-3.png', title: 'Paris', rate: '4.4', country: 'France', oldprice: '699', price: '599'},
    { id: 13, image: 'Deals-card-2.png', title: 'Firenze', rate: '4.5', country: 'Italy', oldprice: '850', price: '750'},
    { id: 14, image: 'Deals-card-2.png', title: 'Firenze', rate: '4.5', country: 'Italy', oldprice: '850', price: '750'},
    { id: 15, image: 'Deals-card-2.png', title: 'Firenze', rate: '4.5', country: 'Italy', oldprice: '850', price: '750'},
    { id: 16, image: 'Deals-card-2.png', title: 'Firenze', rate: '4.5', country: 'Italy', oldprice: '850', price: '750'},
    { id: 17, image: 'Deals-card-1.png', title: 'Madrid', rate: '4.8', country: 'Spain', oldprice: '950', price: '850'},
    { id: 18, image: 'Deals-card-1.png', title: 'Madrid', rate: '4.8', country: 'Spain', oldprice: '950', price: '850'},
    { id: 19, image: 'Deals-card-1.png', title: 'Madrid', rate: '4.8', country: 'Spain', oldprice: '950', price: '850'},
    { id: 20, image: 'Deals-card-1.png', title: 'Madrid', rate: '4.8', country: 'Spain', oldprice: '950', price: '850'},
];
export default cards;